import { Component } from '@angular/core';

@Component({
  selector: 'app-users-table',
  imports: [],
  templateUrl: './users-table.component.html',
})
export class UsersTableComponent {
  users = [
    {
      name: 'Seth Mills',
      email: 'Seth@ropchat.me',
      country: 'USA',
      city: 'Ohio',
      signup: '27 Dec, 2019',
      fans: '169.3K',
      songs: 186,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Abram Workman',
      email: 'AbramK@gmail.com',
      country: 'USA',
      city: 'Alabama',
      signup: '04 Apr, 2016',
      fans: '1.3M',
      songs: 629,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Alfonso',
      email: 'Alfonsoking.12@gmail.com',
      country: 'Brazil',
      city: 'Rio',
      signup: '14 Jun, 2020',
      fans: '537.7K',
      songs: 518,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Ann Schleffer',
      email: 'A.Schle@hotmail.com',
      country: 'USA',
      city: 'Illinois',
      signup: '1 Feb, 2019',
      fans: '531.3K',
      songs: 61,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Jocelyn Bergson',
      email: 'Jocelyn@yahoo.com',
      country: 'France',
      city: 'Paris',
      signup: '19 Sep, 2018',
      fans: '816.2K',
      songs: 79,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Desirae',
      email: 'Desiraem@gmail.com',
      country: 'Canada',
      city: 'Downtown',
      signup: '27 Nov, 2015',
      fans: '638.9K',
      songs: 515,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Martin Ekstrom Bothman',
      email: 'MartineB@yahoo.com',
      country: 'Canada',
      city: 'Toronto',
      signup: '03 Oct, 2016',
      fans: '2.3M',
      songs: 716,
      avatar: 'https://via.placeholder.com/32',
    },
    {
      name: 'Wilson Vaccaro',
      email: 'Wilson@vaccaro.com',
      country: 'USA',
      city: 'New york',
      signup: '14 Sep, 2018',
      fans: '825.1K',
      songs: 372,
      avatar: 'https://via.placeholder.com/32',
    },
  ];
}
